kind: PodPreset
apiVersion: settings.k8s.io/v1alpha1
metadata:
  name: expose-podinfo
spec:
  selector:
    matchLabels:
      app: guestbook
  volumeMounts:
    - name: podinfo
      mountPath: /etc/podinfo
      readOnly: false
  volumes:
    - name: podinfo
      downwardAPI:
        items:
          - path: "labels"
            fieldRef:
              fieldPath: metadata.labels
          - path: "annotations"
            fieldRef:
              fieldPath: metadata.annotations
