---
apiVersion: v1
kind: Service
metadata:
  name: filter
  labels:
    app: filter
    product: guestbook
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: filter
    product: guestbook
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: filter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: filter
        product: guestbook
    spec:
      containers:
      - name: filter
        image: looztra/guestbook-filter:0.6.1-aio
        ports:
        - containerPort: 8080
