---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    app: gateway
    product: guestbook
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: gateway
    product: guestbook
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        product: guestbook
    spec:
      containers:
      - name: gateway
        image: looztra/guestbook-gateway:0.6.1-aio
        ports:
        - containerPort: 8080
        env:
        - name: GATEWAY_GUESTBOOK_ENDPOINTSASSTRING
          value: "storage:8080"
        - name: GATEWAY_FILTER_ENDPOINTSASSTRING
          value: "filter:8080"
