---
apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    app: storage
    product: guestbook
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: storage
    product: guestbook
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: storage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: storage
        product: guestbook
    spec:
      containers:
      - name: storage
        image: looztra/guestbook-storage:0.6.1-aio
        ports:
        - containerPort: 8080
        env:
        - name: GUESTBOOK_BACKEND_REDIS_READ_VIP
          value: "redis"
        - name: GUESTBOOK_BACKEND_REDIS_WRITE_VIP
          value: "redis"
