version: 2

jobs:
  build_backend:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout
      - restore_cache:
          key: guestbook-{{ .Branch }}-{{ checksum "pom.xml" }}
      - run: mvn package
      - save_cache:
          paths:
            - ~/.m2
          key: guestbook-{{ .Branch }}-{{ checksum "pom.xml" }}
      - setup_remote_docker
      - run:
          name: Prepare Artifacts for potential deployment
          command: |
            mkdir -p workspace/artifacts
            echo ${CIRCLE_BUILD_NUM} > workspace/artifacts/circle-build-num.txt
      - run:
          name: Build the docker images
          command: |
            set -x
            echo "Showing of Docker version"
            docker version
            echo "Building the image"
            ./build-images.bash -c -a -n zcicd -v tmp
      - run:
          name: Save docker images
          command: |
            echo "Saving the image for potential deployment"
            docker image ls
            for image in guestbook-filter guestbook-storage guestbook-gateway guestbook-frontend; do
              docker save zcid/${image}:tmp-aio -o workspace/artifacts/docker-img--${image}--tmp-aio
              docker save zcid/${image}:tmp-confd -o workspace/artifacts/docker-img--${image}--tmp-confd
            done
      - persist_to_workspace:
          root: workspace
          paths:
            - artifacts

workflows:
  version: 2
  build_and_test:
    jobs:
      - build_backend
