---
apiVersion: v1
kind: Service
metadata:
  name: filter
  labels:
    component: filter
    app: guestbook
spec:
  selector:
    app: guestbook
    component: filter
  ports:
    - port: 8080
      targetPort: main
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filter
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: filter
        app: guestbook
      annotations:
        io.nodevops/rely-on-confd: "no"
    spec:
      containers:
        - name: filter
          image: looztra/guestbook-filter:0.6.1-aio
          ports:
            - name: main
              containerPort: 8080
