---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    component: frontend
    app: guestbook
spec:
  type: NodePort
  selector:
    app: guestbook
    component: frontend
  ports:
    - name: main
      port: 80
      targetPort: main
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: frontend
        app: guestbook
      annotations:
        io.nodevops/rely-on-ingress: "yes"
        io.nodevops/rely-on-confd: "yes"
    spec:
      containers:
        - name: frontend
          image: looztra/guestbook-frontend:0.5.2-confd
          ports:
          - name: main
            containerPort: 80
          env:
            - name: GUESTBOOK_FRONTEND_API_SERVER_ROOT_URL
              value: "http://guestbook-api.192.168.99.100.xip.io"
