---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    component: gateway
    app: guestbook
spec:
  type: NodePort
  selector:
    app: guestbook
    component: gateway
  ports:
    - name: main
      port: 8080
      targetPort: main
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: gateway
        app: guestbook
      annotations:
        io.nodevops/rely-on-confd: "no"
    spec:
      containers:
        - name: gateway
          image: looztra/guestbook-gateway:0.5.2-aio
          ports:
            - name: main
              containerPort: 8080
          envFrom:
            - configMapRef:
                name: gateway-config
              prefix: GATEWAY_
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: false
          livenessProbe:
            httpGet:
              path: /admin/info
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /admin/info
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
