---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  labels:
    component: gateway
    app: guestbook
spec:
  type: NodePort
  selector:
    app: guestbook
    component: gateway
  ports:
    - name: main
      port: 8080
      targetPort: main
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: gateway
        app: guestbook
    spec:
      containers:
        - name: gateway
          image: looztra/guestbook-gateway:0.6.1-aio
          ports:
            - name: main
              containerPort: 8080
          env:
            - name: GATEWAY_GUESTBOOK_ENDPOINTSASSTRING
              value: "storage:8080"
            - name: GATEWAY_FILTER_ENDPOINTSASSTRING
              value: "filter:8080"
