---
apiVersion: v1
kind: Service
metadata:
  name: redis
  labels:
    app: guestbook
    component: redis
spec:
  selector:
    app: guestbook
    component: redis
  ports:
    - name: redis
      port: 6379
      targetPort: redis
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: guestbook
        component: redis
    spec:
      containers:
        - name: redis
          image: redis:3-alpine
          ports:
            - name: redis
              containerPort: 6379
