---
apiVersion: v1
kind: Service
metadata:
  name: storage
  labels:
    component: storage
    app: guestbook
spec:
  selector:
    component: storage
    app: guestbook
  ports:
    - port: 8080
      targetPort: main
      protocol: TCP
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: storage
spec:
  replicas: 1
  template:
    metadata:
      labels:
        component: storage
        app: guestbook
      annotations:
        io.nodevops/rely-on-confd: "no"
    spec:
      containers:
        - name: storage
          image: looztra/guestbook-storage:0.5.2-aio
          ports:
            - name: main
              containerPort: 8080
          env:
            - name: GUESTBOOK_BACKEND_REDIS_READ_VIP
              value: "redis"
            - name: GUESTBOOK_BACKEND_REDIS_WRITE_VIP
              value: "redis"
          volumeMounts:
            - name: podinfo
              mountPath: /etc/podinfo
              readOnly: false
          livenessProbe:
            httpGet:
              path: /admin/info
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 1
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /admin/info
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 1
            failureThreshold: 3
      volumes:
        - name: podinfo
          downwardAPI:
            items:
              - path: "labels"
                fieldRef:
                  fieldPath: metadata.labels
              - path: "annotations"
                fieldRef:
                  fieldPath: metadata.annotations
